# Generated by Django 3.2.3 on 2021-07-05 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Pais')),
                ('nombrePais', models.CharField(max_length=50, verbose_name='Nombre del Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Registrarse',
            fields=[
                ('rut_colaborador', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut del Colaborador')),
                ('nombre_completo', models.CharField(max_length=65, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('dirección', models.CharField(max_length=30, verbose_name='Dirección')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
                ('contraseña', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaosNews.paises')),
            ],
        ),
    ]
