# Generated by Django 3.2.3 on 2021-07-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarse',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
